# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='verifaction_tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.CharField(max_length=250)),
                ('phonenumber', models.CharField(max_length=250)),
                ('verfication_code', models.IntegerField()),
            ],
        ),
    ]
