# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='location',
        ),
    ]
