# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catergory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to=b'')),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('skd', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('instock', models.IntegerField()),
                ('available',models.BooleanField()),
            ],
        ),
    ]
