# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),

    ]
