# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20181123_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='topcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name_plural': 'topcategory',
            },
        ),
    ]
